name = "oddpack"
author = "clone400"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e77df38a757866f77b7be0f42f4b50681f2a9257db40acb377bdf0fbe7d5a792"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
