name = "oddpack"
author = "clone400"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a82521b6b7419e2cf32b66471b517d8ddffec83d890c5d079eb6f5e28959e910"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
