name = "oddpack"
author = "clone400"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6b47f26302d25ce4f477f4d5adf569a1746b693184ed876eea5060792732f7"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
